version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
#     networks:
#       - frontend_network
# networks:
#   frontend_network:
#     driver: bridge
  